export const addressPricing = [
  {
    name: 'Mogadishu',
    districts: [
      { name: 'Hodan', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Waaberi', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Xamar Jajab', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Howlwadaag', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Xamar Weyne', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Shangaani', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Cabdicasiis', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Shibis', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Boondheere', price: 1, deliveryTime: '90 min', perItem: false },
      { name: 'Kaaraan', price: 1.25, deliveryTime: '90 min', perItem: false },
      { name: 'Deyniile', price: 1.25, deliveryTime: '90 min', perItem: false },
      {
        name: 'Ex-Kontorol',
        price: 1.25,
        deliveryTime: '90 min',
        perItem: false,
      },
      {
        name: 'Suaqa Xoolaha',
        price: 1.5,
        deliveryTime: '90 min',
        perItem: false,
      },
      { name: 'Gubadleey', price: 2, deliveryTime: '90 min', perItem: false },
      { name: 'Cealasha', price: 2, deliveryTime: '90 min', perItem: false },
      { name: 'Kaxda', price: 1.5, deliveryTime: '90 min', perItem: false },
      { name: 'Wadajir', price: 1.5, deliveryTime: '90 min', perItem: false },
      {
        name: 'Garasbaaley',
        price: 1.5,
        deliveryTime: '90 min',
        perItem: false,
      },
      {
        name: 'Yaaqshiid',
        price: 1.25,
        deliveryTime: '90 min',
        perItem: false,
      },
      {
        name: 'Darasalaam',
        price: 1.5,
        deliveryTime: '90 min',
        perItem: false,
      },
      {
        name: 'Dharkeenley',
        price: 1.25,
        deliveryTime: '90 min',
        perItem: false,
      },
      {
        name: 'Wardhigleey',
        price: 1.5,
        deliveryTime: '90 min',
        perItem: false,
      },
      { name: 'Kismaayo', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Hargeysa', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Gaalkacyo', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Boosaaso', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Garowe', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Baydhabo', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Xudur', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Cadaado', price: 1.5, deliveryTime: '3 days', perItem: true },
      {
        name: 'Dhusomareeb',
        price: 1.5,
        deliveryTime: '3 days',
        perItem: true,
      },
      { name: 'Guriceel', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Doolow', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Baraawe', price: 1.5, deliveryTime: '3 days', perItem: true },
      {
        name: 'Garbahaareey',
        price: 1.5,
        deliveryTime: '3 days',
        perItem: true,
      },
      { name: 'Baardheere', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Galdogob', price: 2.5, deliveryTime: '3 days', perItem: true },
      { name: 'Burtinle', price: 2.5, deliveryTime: '3 days', perItem: true },
      { name: 'Boorama', price: 2.5, deliveryTime: '3 days', perItem: true },
      { name: 'Berbera', price: 2.5, deliveryTime: '3 days', perItem: true },
      { name: 'Burco', price: 2.5, deliveryTime: '3 days', perItem: true },
      {
        name: 'Laascaanood',
        price: 2.5,
        deliveryTime: '3 days',
        perItem: true,
      },
      { name: 'Dhoobleey', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Cabudwaaq', price: 1.5, deliveryTime: '3 days', perItem: true },
      { name: 'Qardho', price: 2.5, deliveryTime: '3 days', perItem: true },
    ],
  },
  {
    name: 'Kismaayo',
    districts: [
      { name: 'Kismaayo', price: 1, deliveryTime: '90 min', perItem: false },
    ],
  },
  {
    name: 'Hargeysa',
    districts: [
      { name: 'Hargeysa', price: 1.25, deliveryTime: '90 min', perItem: false },
    ],
  },
  {
    name: 'Baydhabo',
    districts: [
      { name: 'Baydhabo', price: 1, deliveryTime: '90 min', perItem: false },
    ],
  },
]
